FROM mcr.microsoft.com/dotnet/sdk:latest

VOLUME /src
VOLUME /build
VOLUME /deploy

# restore as a separate layer to speed up builds

RUN echo "Restoring"
WORKDIR /src
COPY src/frontend/frontend.csproj .
RUN dotnet restore
RUN echo "Restoring"


RUN echo "Building"
COPY src/frontend/ .
CMD  dotnet publish -c Release -o /deploy/frontend/ 