FROM mcr.microsoft.com/dotnet/sdk:latest AS Build

VOLUME /src
VOLUME /build
VOLUME /deploy

# restore as a separate layer to speed up builds

RUN echo "Restoring"
WORKDIR /src
COPY src/frontend/frontend.csproj .
RUN dotnet restore
RUN echo "Restoring"


RUN echo "Building"
COPY src/frontend/ .
CMD  dotnet publish -c Release -o /deploy/frontend/ 




FROM pulumi/pulumi-dotnet:latest AS Publish

# VOLUME /src
VOLUME /build
VOLUME /deploy

# restore as a separate layer to speed up builds
WORKDIR /deploy
COPY deploy/pulumi/coco-jackalope.csproj .
RUN dotnet restore

COPY deploy/pulumi/ .
RUN  pulumi plugin install

RUN alias puppy='pulumi up -y'
RUN cd pulumi

CMD  pulumi stack select coco-jackalope-dev #&& pulumi up -y
#& dotnet publish -c Release -o /build/pulumi/ 